/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.DayCare;
import Business.Immunization;
import Business.Student;
import Business.VaccineRule;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;
/**
 *
 * @author jxw
 */
public class ImmunizationRecord extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Student student;
    private DayCare daycare;
    /**
     * Creates new form ImmunizationRecord
     */
    public ImmunizationRecord(JPanel upc, Student stu, DayCare dc) {
        initComponents();
        userProcessContainer = upc;
        student = stu;
        daycare = dc;
        refreshPage();
    }
    public void refreshPage(){
        nameText.setText(student.getFirstname()+" "+student.getLastname());
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        birthdayText.setText(fm.format(student.getBirthday()));
        int[] mmrperiod =Immunization.getVaccineRules().get(0).getPeriod();
        int[] cpperiod = Immunization.getVaccineRules().get(1).getPeriod();
        int[] dtapperiod = Immunization.getVaccineRules().get(2).getPeriod();
        int[] hibperiod = Immunization.getVaccineRules().get(3).getPeriod();
        Calendar[] vaccineTime = new Calendar[8];
        for(int i = 0; i<8; i++){
            vaccineTime[i] = Calendar.getInstance();
            vaccineTime[i].setTime(student.getBirthday());
        }
       vaccineTime[0].add(Calendar.MONTH, mmrperiod[0]);
       vaccineTime[1].add(Calendar.MONTH, mmrperiod[1]);
       vaccineTime[2].add(Calendar.MONTH, cpperiod[0]);
       vaccineTime[3].add(Calendar.MONTH, dtapperiod[0]);
       vaccineTime[4].add(Calendar.MONTH, dtapperiod[1]);
       vaccineTime[5].add(Calendar.MONTH, dtapperiod[2]);
       vaccineTime[6].add(Calendar.MONTH, hibperiod[0]);
       vaccineTime[7].add(Calendar.MONTH, hibperiod[1]);
       Date[] time = new Date[8];
       for(int i = 0; i<8; i++){
           time[i] = vaccineTime[i].getTime();
       }
        mmr1Text.setText(fm.format(time[0]));
        mmr2Text.setText(fm.format(time[1]));
        chickenpox1Text.setText(fm.format(time[2]));
        dtap1Text.setText(fm.format(time[3]));
        dtap2Text.setText(fm.format(time[4]));
        dtap3Text.setText(fm.format(time[5]));
        hib1Text.setText(fm.format(time[6]));
        hib2Text.setText(fm.format(time[7]));
        boolean[] injected = student.getImmus().getInjected();
        if(injected[0]) mmr1Box.setSelected(true);
        if(injected[1]) mmr2Box.setSelected(true);
        if(injected[2]) chickenpox1Box.setSelected(true);
        if(injected[3]) dtap1Box.setSelected(true);
        if(injected[4]) dtap2Box.setSelected(true);
        if(injected[5]) dtap3Box.setSelected(true);
        if(injected[6]) hib1Box.setSelected(true);
        if(injected[7]) hib2Box.setSelected(true);
        
        //show vaccine rules;
        String vacRule = "";
        for(VaccineRule vr: Immunization.getVaccineRules()){
            String period= "";
            for(int i: vr.getPeriod()){
                period += i+" ";
            }
            
            vacRule += vr.getName()+": "+vr.getTimes()+"times, "+"Month "+period+"\n";
        }
        immuStandardText.setText(vacRule);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        immunizationRecordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        mmrLabel = new javax.swing.JLabel();
        mmr1Text = new javax.swing.JTextField();
        chickenpoxLabel = new javax.swing.JLabel();
        chickenpox1Text = new javax.swing.JTextField();
        dtapLabel = new javax.swing.JLabel();
        dtap1Text = new javax.swing.JTextField();
        hibLabel = new javax.swing.JLabel();
        hib1Text = new javax.swing.JTextField();
        dtap2Text = new javax.swing.JTextField();
        dtap3Text = new javax.swing.JTextField();
        hib2Text = new javax.swing.JTextField();
        mmr2Text = new javax.swing.JTextField();
        alterBtn = new javax.swing.JButton();
        mmr1Box = new javax.swing.JCheckBox();
        chickenpox1Box = new javax.swing.JCheckBox();
        dtap1Box = new javax.swing.JCheckBox();
        hib1Box = new javax.swing.JCheckBox();
        mmr2Box = new javax.swing.JCheckBox();
        dtap3Box = new javax.swing.JCheckBox();
        hib2Box = new javax.swing.JCheckBox();
        dtap2Box = new javax.swing.JCheckBox();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        immuStandardText = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        birthdayText = new javax.swing.JTextField();

        immunizationRecordLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        immunizationRecordLabel.setText("Immunization Record");

        nameLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        nameLabel.setText("Name:");

        nameText.setEditable(false);
        nameText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        mmrLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        mmrLabel.setText("MMR");

        mmr1Text.setEditable(false);
        mmr1Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        chickenpoxLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        chickenpoxLabel.setText("chickenpox");

        chickenpox1Text.setEditable(false);
        chickenpox1Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        dtapLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        dtapLabel.setText("DTaP");

        dtap1Text.setEditable(false);
        dtap1Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        hibLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        hibLabel.setText("Hib");

        hib1Text.setEditable(false);
        hib1Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        dtap2Text.setEditable(false);
        dtap2Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        dtap3Text.setEditable(false);
        dtap3Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        hib2Text.setEditable(false);
        hib2Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        mmr2Text.setEditable(false);
        mmr2Text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        alterBtn.setText("Alter Immunization Record");
        alterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterBtnActionPerformed(evt);
            }
        });

        mmr1Box.setEnabled(false);
        mmr1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmr1BoxActionPerformed(evt);
            }
        });

        chickenpox1Box.setEnabled(false);
        chickenpox1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenpox1BoxActionPerformed(evt);
            }
        });

        dtap1Box.setEnabled(false);
        dtap1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtap1BoxActionPerformed(evt);
            }
        });

        hib1Box.setEnabled(false);
        hib1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hib1BoxActionPerformed(evt);
            }
        });

        mmr2Box.setEnabled(false);
        mmr2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmr2BoxActionPerformed(evt);
            }
        });

        dtap3Box.setEnabled(false);
        dtap3Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtap3BoxActionPerformed(evt);
            }
        });

        hib2Box.setEnabled(false);
        hib2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hib2BoxActionPerformed(evt);
            }
        });

        dtap2Box.setEnabled(false);
        dtap2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtap2BoxActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        immuStandardText.setEditable(false);
        immuStandardText.setColumns(20);
        immuStandardText.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        immuStandardText.setRows(5);
        immuStandardText.setEnabled(false);
        jScrollPane1.setViewportView(immuStandardText);

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("Birthday:");

        birthdayText.setEditable(false);
        birthdayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dtapLabel)
                                    .addComponent(hibLabel)))
                            .addComponent(chickenpoxLabel)
                            .addComponent(mmrLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(84, 84, 84)
                                .addComponent(saveBtn)
                                .addGap(44, 44, 44)
                                .addComponent(alterBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dtap1Text)
                                    .addComponent(mmr1Text, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chickenpox1Text, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hib1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mmr1Box)
                                            .addComponent(dtap1Box)
                                            .addComponent(hib1Box))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dtap2Text)
                                            .addComponent(mmr2Text)
                                            .addComponent(hib2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(chickenpox1Box))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mmr2Box)
                                            .addComponent(hib2Box)
                                            .addComponent(dtap2Box))
                                        .addGap(18, 18, 18)
                                        .addComponent(dtap3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dtap3Box))
                                    .addComponent(jScrollPane1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(birthdayText, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(nameText))
                        .addGap(52, 52, 52)
                        .addComponent(immunizationRecordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(immunizationRecordLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(birthdayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mmr1Box, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mmrLabel)
                                .addComponent(mmr1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chickenpoxLabel)
                                .addComponent(chickenpox1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chickenpox1Box))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dtapLabel)
                                .addComponent(dtap1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dtap1Box))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hib1Box)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hibLabel)
                                .addComponent(hib1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mmr2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mmr2Box))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtap2Box)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dtap2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dtap3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dtap3Box))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hib2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hib2Box))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterBtn)
                    .addComponent(backBtn)
                    .addComponent(saveBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void alterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterBtnActionPerformed
        alterBtn.setEnabled(false);
        saveBtn.setEnabled(true);
        backBtn.setEnabled(false);
        mmr1Box.setEnabled(true);
        mmr2Box.setEnabled(true);
        chickenpox1Box.setEnabled(true);
        dtap1Box.setEnabled(true);
        dtap2Box.setEnabled(true);
        dtap3Box.setEnabled(true);
        hib1Box.setEnabled(true);
        hib2Box.setEnabled(true);
        
        
    }//GEN-LAST:event_alterBtnActionPerformed

    private void mmr1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmr1BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmr1BoxActionPerformed

    private void chickenpox1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenpox1BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenpox1BoxActionPerformed

    private void dtap1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtap1BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtap1BoxActionPerformed

    private void hib1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hib1BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hib1BoxActionPerformed

    private void mmr2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmr2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmr2BoxActionPerformed

    private void dtap3BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtap3BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtap3BoxActionPerformed

    private void hib2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hib2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hib2BoxActionPerformed

    private void dtap2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtap2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtap2BoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageStudent msPanel = (ManageStudent) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        alterBtn.setEnabled(true);
        saveBtn.setEnabled(false);
        backBtn.setEnabled(true);
        mmr1Box.setEnabled(false);
        mmr2Box.setEnabled(false);
        chickenpox1Box.setEnabled(false);
        dtap1Box.setEnabled(false);
        dtap2Box.setEnabled(false);
        dtap3Box.setEnabled(false);
        hib1Box.setEnabled(false);
        hib2Box.setEnabled(false);
        
        boolean[] newinjected = new boolean[8];
        
        if(mmr1Box.isSelected()){
            newinjected[0] = true;
        }else{
            newinjected[0] = false;
        }
        if(mmr2Box.isSelected()){
            newinjected[1] = true;
        }else{
            newinjected[1] = false;
        }
        if(chickenpox1Box.isSelected()){
            newinjected[2] = true;
        }else{
            newinjected[2] = false;
        }
        if(dtap1Box.isSelected()){
            newinjected[3] = true;
        }else{
            newinjected[3] = false;
        }
        if(dtap2Box.isSelected()){
            newinjected[4] = true;
        }else{
            newinjected[4] = false;
        }
        if(dtap3Box.isSelected()){
            newinjected[5] = true;
        }else{
            newinjected[5] = false;
        }
        if(hib1Box.isSelected()){
            newinjected[6] = true;
        }else{
            newinjected[6] = false;
        }
        if(hib2Box.isSelected()){
            newinjected[7] = true;
        }else{
            newinjected[7] = false;
        }
        student.getImmus().setInjected(newinjected);
        daycare.writeImmuCsv();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void birthdayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField birthdayText;
    private javax.swing.JCheckBox chickenpox1Box;
    private javax.swing.JTextField chickenpox1Text;
    private javax.swing.JLabel chickenpoxLabel;
    private javax.swing.JCheckBox dtap1Box;
    private javax.swing.JTextField dtap1Text;
    private javax.swing.JCheckBox dtap2Box;
    private javax.swing.JTextField dtap2Text;
    private javax.swing.JCheckBox dtap3Box;
    private javax.swing.JTextField dtap3Text;
    private javax.swing.JLabel dtapLabel;
    private javax.swing.JCheckBox hib1Box;
    private javax.swing.JTextField hib1Text;
    private javax.swing.JCheckBox hib2Box;
    private javax.swing.JTextField hib2Text;
    private javax.swing.JLabel hibLabel;
    private javax.swing.JTextArea immuStandardText;
    private javax.swing.JLabel immunizationRecordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mmr1Box;
    private javax.swing.JTextField mmr1Text;
    private javax.swing.JCheckBox mmr2Box;
    private javax.swing.JTextField mmr2Text;
    private javax.swing.JLabel mmrLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
