/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import Business.DayCare;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author jxw
 */
public class MainJFrame extends javax.swing.JFrame {
    private DayCare daycare;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() throws ParseException {
        initComponents();
        daycare = new DayCare();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        rightBtnPanel = new javax.swing.JPanel();
        manageStuBtn = new javax.swing.JButton();
        manageTchBtn = new javax.swing.JButton();
        roomArrangeBtn = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageStuBtn.setText("Manage Student");
        manageStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStuBtnActionPerformed(evt);
            }
        });

        manageTchBtn.setText("Manage Teacher");
        manageTchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTchBtnActionPerformed(evt);
            }
        });

        roomArrangeBtn.setText("Classroom Arrangement");
        roomArrangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomArrangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightBtnPanelLayout = new javax.swing.GroupLayout(rightBtnPanel);
        rightBtnPanel.setLayout(rightBtnPanelLayout);
        rightBtnPanelLayout.setHorizontalGroup(
            rightBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageStuBtn)
                    .addComponent(manageTchBtn)
                    .addComponent(roomArrangeBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightBtnPanelLayout.setVerticalGroup(
            rightBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightBtnPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(manageStuBtn)
                .addGap(30, 30, 30)
                .addComponent(manageTchBtn)
                .addGap(33, 33, 33)
                .addComponent(roomArrangeBtn)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(rightBtnPanel);

        userProcessContainer.setPreferredSize(new java.awt.Dimension(900, 600));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStuBtnActionPerformed

        ManageStudent panel = new ManageStudent(userProcessContainer, daycare);
        userProcessContainer.add("ManageStudent", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStuBtnActionPerformed

    private void manageTchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTchBtnActionPerformed
        ManageTeacher panel = new ManageTeacher(userProcessContainer, daycare);
        userProcessContainer.add("ManageTeacher", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageTchBtnActionPerformed

    private void roomArrangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomArrangeBtnActionPerformed
        ArrangeClassroom panel = new ArrangeClassroom(userProcessContainer, daycare);
        userProcessContainer.add("ArrangeClassroom", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_roomArrangeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageStuBtn;
    private javax.swing.JButton manageTchBtn;
    private javax.swing.JPanel rightBtnPanel;
    private javax.swing.JButton roomArrangeBtn;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
