/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.DayCare;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Student;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jxw
 */
public class ManageStudent extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private DayCare daycare;
    /**
     * Creates new form ManageStudent
     */
    public ManageStudent(JPanel upc,DayCare dc) {
        initComponents();
        userProcessContainer = upc;
        daycare = dc;
        refreshTable();
    }
    
    public void refreshTable() {
        int rowCount = studentTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)studentTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
        
        for(Student s : daycare.getStudents()) {
            Object row[] = new Object[6];
            row[0] = s.getFirstname();
            row[1] = s.getLastname();
            row[2] = s.getId();
            row[3] = s.getAge();
            SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
            row[4] = fm.format(s.getRegistrationDate());
            
            Date anniversary = s.getRegistrationDate();
            Calendar myCal = Calendar.getInstance();
            myCal.setTime(anniversary);    
            myCal.add(Calendar.YEAR, +1);    
            anniversary = myCal.getTime();
            row[5] = fm.format(anniversary);
            model.addRow(row);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        addStuBtn = new javax.swing.JButton();
        deleteStuBtn = new javax.swing.JButton();
        viewImmuBtn = new javax.swing.JButton();
        stuinfoLabel = new javax.swing.JLabel();

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "ID", "Age", "Registration Date", "Registration Anniversary"
            }
        ));
        jScrollPane1.setViewportView(studentTable);
        if (studentTable.getColumnModel().getColumnCount() > 0) {
            studentTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            studentTable.getColumnModel().getColumn(1).setPreferredWidth(40);
            studentTable.getColumnModel().getColumn(2).setPreferredWidth(12);
            studentTable.getColumnModel().getColumn(3).setPreferredWidth(12);
        }

        addStuBtn.setText("Add Student");
        addStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuBtnActionPerformed(evt);
            }
        });

        deleteStuBtn.setText("Delete Student");
        deleteStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStuBtnActionPerformed(evt);
            }
        });

        viewImmuBtn.setText("View Immunization Record");
        viewImmuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewImmuBtnActionPerformed(evt);
            }
        });

        stuinfoLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        stuinfoLabel.setText("Student Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewImmuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteStuBtn)
                        .addGap(85, 85, 85)
                        .addComponent(addStuBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stuinfoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(stuinfoLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStuBtn)
                    .addComponent(deleteStuBtn)
                    .addComponent(viewImmuBtn))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuBtnActionPerformed
        AddStudent as = new AddStudent(userProcessContainer,daycare);
        userProcessContainer.add("AddStudent", as);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addStuBtnActionPerformed

    private void viewImmuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewImmuBtnActionPerformed
        int row = studentTable.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for(Student stu: daycare.getStudents()){
            if(stu.getId().equals(studentTable.getValueAt(row, 2))){
                ImmunizationRecord ir = new ImmunizationRecord(userProcessContainer, stu, daycare);
                userProcessContainer.add("ImmunizationRecord", ir);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                break;
            }
        }
       
        
    }//GEN-LAST:event_viewImmuBtnActionPerformed

    private void deleteStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStuBtnActionPerformed
        int row = studentTable.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for(Student stu: daycare.getStudents()){
            if(stu.getId() == studentTable.getValueAt(row, 2) && stu.getFirstname() == studentTable.getValueAt(row, 0)){
                daycare.deleteStudent(stu);
                JOptionPane.showMessageDialog(null, "Student deleted successfully.");
                break;
            }
                
            
        }
       
        refreshTable();
    }//GEN-LAST:event_deleteStuBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStuBtn;
    private javax.swing.JButton deleteStuBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentTable;
    private javax.swing.JLabel stuinfoLabel;
    private javax.swing.JButton viewImmuBtn;
    // End of variables declaration//GEN-END:variables

   
}
